export const START_FETCH_PODCAST = 'podcast/START_FETCH_PODCAST'
export const SET_PODCAST = 'podcast/SET_PODCAST'

export const START_FETCH_MORE_EPISODES = 'podcast/START_FETCH_MORE_EPISODES'
export const SET_MORE_EPISODES = 'podcast/SET_MORE_EPISODES'

export const START_FETCH_RECOMMENDATIONS = 'podcast/START_FETCH_RECOMMENDATIONS'
export const SET_RECOMMENDATIONS = 'podcast/SET_RECOMMENDATIONS'
