const PodcastTypes = {
    FETCH_PODCAST: 'podcast/FETCH_PODCAST',
    FETCH_PODCAST_START: 'podcast/FETCH_PODCAST_START',
    FETCH_PODCAST_SUCCESS: 'podcast/FETCH_PODCAST_SUCCESS',
    FETCH_PODCAST_FAILURE: 'podcast/FETCH_PODCAST_FAILURE',

    FETCH_MORE_EPISODES: 'podcast/FETCH_MORE_EPISODES',
    FETCH_MORE_EPISODES_START: 'podcast/FETCH_MORE_EPISODES_START',
    FETCH_MORE_EPISODES_SUCCESS: 'podcast/FETCH_MORE_EPISODES_SUCCESS',
    FETCH_MORE_EPISODES_FAILURE: 'podcast/FETCH_MORE_EPISODES_FAILURE',

    FETCH_RECOMMENDATIONS: 'podcast/FETCH_RECOMMENDATIONS',
    FETCH_RECOMMENDATIONS_START: 'podcast/FETCH_RECOMMENDATIONS_START',
    FETCH_RECOMMENDATIONS_SUCCESS: 'podcast/FETCH_RECOMMENDATIONS_SUCCESS',
    FETCH_RECOMMENDATIONS_FAILURE: 'podcast/FETCH_RECOMMENDATIONS_FAILURE',
}

export default PodcastTypes
