const DiscoverTypes = {
    NEXT_PAGE: 'discover/NEXT_PAGE',

    FETCH_PODCAST_LISTS: 'discover/FETCH_PODCAST_LISTS',
    FETCH_PODCAST_LISTS_START: 'discover/FETCH_PODCAST_LISTS_START',
    FETCH_PODCAST_LISTS_SUCCESS: 'discover/FETCH_PODCAST_LISTS_SUCCESS',
    FETCH_PODCAST_LISTS_FAILURE: 'discover/FETCH_PODCAST_LISTS_FAILURE',
}

export default DiscoverTypes
